[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'


[[plugins]]
repo = 'itchyny/vim-haskell-indent'

[[plugins]]
repo = 'raichoo/haskell-vim'

[[plugins]]
repo = 'elzr/vim-json'
